EnrollmentApplication2/EnrollmentApplication/Models/Enrollment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace EnrollmentApplication.Models
{
    public class Enrollment
    {
        public virtual int EnrollmentId { get; set; }

        public virtual int StudentId { get; set; }

        public virtual int CourseId { get; set; }

        [Display(Name = "Grade")]
        [Required]
        [RegularExpression("A - F", ErrorMessage = "Grade must be letter value")]
        public virtual string Grade { get; set; }

        public virtual Student Student { get; set; }

        public virtual Course Course { get; set; }

        public virtual bool IsActive { get; set; }

        [Display(Name = "Assigned Campus")]
        [Required(ErrorMessage = "Assigned Campus cannot be blank")]
        public virtual string AssignedCampus { get; set; }

        [Display(Name = "Enrolled in Semester")]
        [Required(ErrorMessage = "Semester cannot be blank")]
        public virtual string EnrollmentSemester { get; set; }

        [Display(Name = "Enrollment Year")]
        [Required]
        [Range (2018, 9999, ErrorMessage = "Year cannot be less than 2018")]
        public virtual int EnrollmentYear { get; set; }
    }
}

EnrollmentApplication2/EnrollmentApplication/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnrollmentApplication.Models;

namespace EnrollmentApplication.Controllers
{
    public class EnrollmentsController : Controller
    {
        private EnrollmentDBContext db = new EnrollmentDBContext();

        // GET: Enrollments
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(enrollments.ToList());
        }

        
        
            public ActionResult StudentofTheMonth()
            {
                var student = GetStudentofTheMonth();
                return PartialView("_StudentofTheMonth");
            }
        
        private Student GetStudentofTheMonth()
        {
            var student = db.Students.OrderBy(a => System.Guid.NewGuid()).First();

            return student;
        }
        
        // Student Search
        public ActionResult StudentSearch(string q)
        {
            var students = GetStudents(q);
            return PartialView(students);
        }

        private List<Student> GetStudents(String searchstring)
        {
            return db.Students.Where(a => a.LastName.Contains(searchstring)).ToList();
        }

        // Course Search
        public ActionResult CourseSearch(string a)
        {
            var courses = GetCourses(a);
            return PartialView(courses);
        }

        private List<Course> GetCourses(String searchstring)
        {
            return db.Courses.Where(a => a.Title.Contains(searchstring)).ToList();
        }



        // GET: Enrollments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollments/Create
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title");
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnrollmentId,StudentId,CourseId,Grade,IsActive,AssignedCampus,EnrollmentSemester,EnrollmentYear")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName", enrollment.StudentId);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnrollmentId,StudentId,CourseId,Grade,IsActive,AssignedCampus,EnrollmentSemester,EnrollmentYear")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Title", enrollment.CourseId);
            ViewBag.StudentId = new SelectList(db.Students, "StudentId", "LastName", enrollment.StudentId);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/CourseSearch.cshtml
@model IEnumerable<EnrollmentApplication.Models.Course>

<div id="searchresults2">
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.Title</li>
        }
    </ul>
</div>

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/Create.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enrollment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedCampus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AssignedCampus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignedCampus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentSemester, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "EnrollmentSemester", "Spring")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "EnrollmentSemester", "Summer")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "EnrollmentSemester", "Fall")
                @Html.ValidationMessageFor(model => model.EnrollmentSemester, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EnrollmentYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/Delete.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedCampus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedCampus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentSemester)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentYear)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/Details.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Enrollment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedCampus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedCampus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentSemester)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentYear)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EnrollmentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/Edit.cshtml
@model EnrollmentApplication.Models.Enrollment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enrollment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EnrollmentId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedCampus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AssignedCampus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignedCampus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentSemester, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "EnrollmentSemester", "Spring")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "EnrollmentSemester", "Summer")
                @Html.RadioButtonFor(model => model.EnrollmentSemester, "EnrollmentSemester", "Fall")

                @Html.ValidationMessageFor(model => model.EnrollmentSemester, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EnrollmentYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/Index.cshtml
@model IEnumerable<EnrollmentApplication.Models.Enrollment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div id="studentofthemonth">
    @Ajax.ActionLink("Click here for the student of the month!",
    "StudentofTheMonth",
    null,
    new AjaxOptions
    {
        UpdateTargetId = "studentofthemonth",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET"
    },
    new { @class = "btn btn-primary"})
</div>



<div class="panel panel-default">
    <div class="panel-heading">Student Search</div>
    <div class="panel-body">
        @using (
            Ajax.BeginForm("StudentSearch", "Enrollments",
            new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                UpdateTargetId = "searchresults",
                LoadingElementId = "ajax-loader",
                OnFailure = "searchFailed"
            }
            )
            )
        {
            <input type="text" name="q" />
            <input type="submit" value="search" />
            <img id="ajax-loader" src="@Url.Content("~/Images/ajax-loader.gif")" style="display:none" />
        }

        <div id="searchresults">

        </div>

    </div>

</div>


<div class="panel panel-default">
    <div class="panel-heading">Course Search</div>
    <div class="panel-body">
        @using (
                Ajax.BeginForm("CourseSearch", "Enrollments",
                new AjaxOptions
                {
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "GET",
                    UpdateTargetId = "searchresults",
                    LoadingElementId = "ajax-loader",
                    OnFailure = "searchFailed"
                }
                )
                )
        {
            <input type="text" name="q" />
            <input type="submit" value="search" />
            <img id="ajax-loader" src="@Url.Content("~/Images/ajax-loader.gif")" style="display:none" />
        }

        <div id="searchresults2">

        </div>

    </div>

</div>





<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedCampus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollmentSemester)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrollmentYear)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grade)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignedCampus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EnrollmentSemester)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EnrollmentYear)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EnrollmentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EnrollmentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EnrollmentId })
        </td>
    </tr>
}

</table>

@section Scripts
{
    <scripts src="~/Scripts/jquery.validate.unobtrusive.min.js"></scripts>
    <script src="~/Scripts/Apps/EnrollmentsScript.js"></script>
}

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/StudentSearch.cshtml
@model IEnumerable<EnrollmentApplication.Models.Student>

<div id="searchresults">
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.LastName</li>
        }
    </ul>
</div>

EnrollmentApplication2/EnrollmentApplication/Views/Enrollments/_StudentofTheMonth.cshtml
@model EnrollmentApplication.Models.Student
<h2>
    Student of the Month
</h2>
<div class="panel">
    <div class="panel-heading">
        Here's is our Student from Student of the Month
    </div>
    <div class="panel-body">
        <p>First Name: @Model.FirstName</p>
        <p>Last Name: @Model.LastName</p>
    </div>
</div>